# Generated by Django 3.1.4 on 2020-12-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donation_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
