# Generated by Django 3.1.4 on 2020-12-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_charity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='user',
        ),
    ]
