# Generated by Django 3.1.4 on 2020-12-16 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0003_donation_slug'),
        ('charity', '0003_remove_charity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='Name',
        ),
        migrations.AddField(
            model_name='charity',
            name='Charity_Donations_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donation'),
        ),
        migrations.AddField(
            model_name='charity',
            name='Charity_Phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charity',
            name='Charity_Slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='Charity_user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
