# Generated by Django 3.1.4 on 2020-12-18 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donation_slug'),
        ('charity', '0004_auto_20201217_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='Charity_Donations_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='donation.donation'),
            preserve_default=False,
        ),
    ]
