# Generated by Django 3.1.4 on 2020-12-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donation_slug'),
        ('charity', '0005_auto_20201218_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='Charity_Donations_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donation'),
        ),
    ]
