# Generated by Django 3.1.4 on 2020-12-28 18:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_auto_20201218_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Phone_Number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('Social_Status', models.CharField(max_length=50)),
                ('Family_Members_Number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='charity',
            name='Charity_Phone_Number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='charity',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.beneficiary'),
        ),
    ]
