# Generated by Django 3.1.4 on 2020-12-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_auto_20201228_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='beneficiary',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charity.charity'),
        ),
    ]
