# Generated by Django 3.1.4 on 2020-12-15 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0003_donation_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donor_Name', models.CharField(max_length=30)),
                ('Donor_Slug', models.SlugField(blank=True, null=True)),
                ('Donor_Email', models.EmailField(max_length=254)),
                ('Donar_Employmenr_Type', models.CharField(max_length=30)),
                ('Donor_Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Donor_Donations_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donation')),
                ('Donor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Charity_Name', models.CharField(max_length=30)),
                ('Charity_Slug', models.SlugField(blank=True, null=True)),
                ('Charity_Email', models.EmailField(max_length=254)),
                ('Charity_Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Charity_Donations_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donation')),
                ('Charity_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
