# Generated by Django 3.1.4 on 2020-12-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_charity_charity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='Donor_Name',
        ),
    ]
