# Generated by Django 3.1.4 on 2020-12-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_donor_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='Donor_Name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
