# Generated by Django 3.1.4 on 2020-12-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='Social_State',
            new_name='Social_Status',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='Charity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to='charity.charity'),
            preserve_default=False,
        ),
    ]
