# Generated by Django 3.1.4 on 2020-12-15 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_remove_charity_user'),
        ('beneficiary', '0002_auto_20201214_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='Charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to='charity.charity'),
        ),
    ]
